### PR TITLE
feat: add client authentication strategy

### PR DESCRIPTION
**Pull request by narg95**
## Related issue

#564 

## Proposed changes

- Add a `ClientAuthenticationStrategy` type to provide an extension point for custom client authentication methods
- Add `Fosite.DefaultClientAuthentication` as fosite's default and backward compatible client authentication strategy. Its content is 100% the current fosite's client authentication logic
- Add method `Fosite.WithDefaultClientAuthentication` to use fosite's default client authentication strategy

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ x] I have added tests that prove my fix is effective or that my feature
      works.
- [x ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
Thank you, this makes sense to me!

However, I think it would make sense to have a small helper function like `f.authenticateClient()` which returns the default strategy unless another strategy was set. This will prevent potential panics for people who forget to call `WithDefaultClientAuthentication`

**Comment by narg95** [comment]
> However, I think it would make sense to have a small helper function like `f.authenticateClient()` which returns the default strategy unless another strategy was set. This will prevent potential panics for people who forget to call `WithDefaultClientAuthentication`

great idea, it's done! Actually it made the pull request is even smaller

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Comment by aeneasr** [comment]
Oh, unfortunately, for some reason, the CircleCI tests are not running. Do you maybe have a fork on CircleCI of ory/fosite that you follow? If so, you need to unsubscribe / unwatch that fork. Then, you need to make another push to your branch using:

```
$ git commit --amend --allow-empty
$ git push --force
```

That should get the CI running! Thank you :)

**Comment by narg95** [comment]
It works now. I did nothing with CircleCI. I unsubscribed my branch from Travis-CI and amended the commit. One of the two made it work :)

**Comment by aeneasr** [comment]
Nice, thank you! :)

**Pull request merged**
