### PR TITLE
Get the token from the access_token query parameter

### PR DESCRIPTION
**Pull request by janekolszak**
As discussed on Gitter some time ago - fosite needs to use _access_token_ query param. (https://tools.ietf.org/html/rfc6750)

### CODE REVIEW

**Comment by arekkas** [comment]
Thank you for your contribution!

Unfortunately, the tests are failing. Most likely because `req.URL.Query()` has not been mocked properly in the tests. While you're add it, could you please add a test for query-based access token verification as well?

Also, could you please sign our [DOC](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md#developers-certificate-of-origin) :)

**Comment by arekkas** [comment]
Let me know when you're ready for review :) Stupid coveralls...

**Comment by janekolszak** [comment]
It's ready.
I was lazy and tried to use CI for development. In the end had to setup test on my local env. :smi

I'm not sure about `ParseForm`. It seems to parse more than needed, but I can't find anything that parses only URL.

**Comment by arekkas** [comment]
Perfect, thank you! Now one last thing, could you please sign the DOC with `git commit --amend -s`? :)

**Comment by janekolszak** [comment]
Done

**Comment by arekkas** [comment]
Thank you!

**Pull request merged**
