### PR TITLE
feat: add ResponseModeHandler to support custom response modes

### PR DESCRIPTION
**Pull request by narg95**
## Related issue

#591 

## Proposed changes

This is a *draft/preview* PR of the proposed change described in issue #591 

**Status**

* Main functionality is implemented
* Existing Unit tests pass
* Missing: 
    * Add `ResponseModeHandler` in `compose.Config` package
    * Add extra unit test 
    * Document public interface and source code

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x ] I have added tests that prove my fix is effective or that my feature
      works.
- [x ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
I think this is going in the right direction! Would definitely need a few more tests, especially integration tests :)

**Comment by narg95** [comment]
sure, bu I was thinking in unit tests, why did you consider integration tests if this change is not integrating with a DB or external processes, or what kind of integration tests you mean? Can you point me in the right direction?

**Comment by aeneasr** [comment]
Ah sure, I was thinking of a test in the direction of https://github.com/ory/fosite/blob/master/integration/authorize_form_post_test.go which would use a custom response mode. Does that make sense?

**Comment by narg95** [comment]
Sure, makes sense, I will use it as a base

**Comment by aeneasr** [comment]
Once https://github.com/ory/hydra/pull/2526 is merged we can re-run the conformity tests here which should then pass :)

**Comment by narg95** [comment]
@aeneasr today's merged commits in hydra and fosite seem to work :)
I rebased this branch with latest commits and got OpenID Connect Conformity Tests 🟢  green :)

**Review by aeneasr — APPROVED** [review]
Awesome, thank you for your contribution!

**Pull request merged**
