### PR TITLE
fix: Fixed the missing state check for hybrid flow

### PR DESCRIPTION
**Pull request by harjoben**
## Related Issue or Design Document
https://github.com/ory/fosite/issues/669 has the details of the bug

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by harjoben** [comment]
@aeneasr The tests here are failing because they are being run in a go1.14 environment. The `Has()` method for `url.Values` is only available from go1.17 onwards. Do the tests need to be updated to use the latest go version? Or I should update my fix to not use the `Has()` method?

**Comment by james-d-elliott** [comment]
> @aeneasr The tests here are failing because they are being run in a go1.14 environment. The `Has()` method for `url.Values` is only available from go1.17 onwards. Do the tests need to be updated to use the latest go version? Or I should update my fix to not use the `Has()` method?

Probably the most accessible option would be to do something along the lines of this since the url.Values are just a `map[string][]string`:

```go
	if _, ok :=resp.GetParameters()["state"]; !ok {
		resp.AddParameter("state", ar.GetState())
	}
```

**Comment by aeneasr** [comment]
We can move to Go 1.17 :)

**Comment by harjoben** [comment]
> We can move to Go 1.17 :)

@aeneasr How do we go about doing that? I don't believe I have access to update the circleci tests running for this PR.

**Comment by harjoben** [comment]
@aeneasr I believe Go was upgraded already. I don't have permissions to re-run the checks for this PR. Can you help me do that?

**Comment by james-d-elliott** [comment]
> @aeneasr I believe Go was upgraded already. I don't have permissions to re-run the checks for this PR. Can you help me do that?

If you merge master into your local branch and push that it should trigger a rebuild.

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
@harjoben can you add a test that fails the current code on master and passes with the changes you've made? Thank you!

**Comment by aeneasr** [comment]
@harjoben are you still up for the changes?

**Comment by harjoben** [comment]
> @harjoben are you still up for the changes?

@aeneasr Yes, I will make the changes. Give me some time. Apologies for dragging this so long

**Comment by aeneasr** [comment]
no problem :)

**Comment by harjoben** [comment]
@aeneasr I have added the relevant test.

**Comment by james-d-elliott** [comment]
Can confirm the test fails before the fix, have not checked post fix as I'm assuming circleci will fail the check if it doesn't.

**Comment by aeneasr** [comment]
thank you!

**Pull request merged**
