### PR TITLE
fix: upgrade gogo protubuf

### PR DESCRIPTION
**Pull request by vineet-garg**
## Related issue
This should fix Nancy scan failure

## Proposed changes
upgrade gogo/protobuf version

## Checklist

- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ x] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by vineet-garg** [comment]
FYI: I did not edit the files in this commit. All I had to do was run a command ```go get github.com/gogo/protobuf@v1.3.2``` The changes made to the go.mod and go.sum files were automatic as a result of the above command.

**Comment by zepatrik** [comment]
I just updated the downstream package, can you also bump it? https://github.com/ory/x/releases/tag/v0.0.212

**Comment by vineet-garg** [comment]
> I just updated the downstream package, can you also bump it? https://github.com/ory/x/releases/tag/v0.0.212
> This should solve the problems in this repo.

Done

**Comment by aeneasr** [comment]
Thank you!

**Pull request merged**
