### PR TITLE
fix: use bitwise comparison for jwt validation errors

### PR DESCRIPTION
**Pull request by narg95**
## Issue
 Reported by @mitar [here](https://github.com/ory/fosite/pull/593#discussion_r707260514)

## Description

Use bitwise comparison for validation errors instead of `==`.

A JWT validation error can encode multiple errors in one instance, therefore a simple `==` is only effective on single errors, but not with multiple. A proper comparison must use bit masking `if ( _ & _ ) != 0`.
This PR finds and fixes the places where this comparison occurs.

## Checklist

- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x ] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x ] I have added tests that prove my fix is effective or that my feature
      works.
- [x ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by james-d-elliott** [comment]
> 
> 
> @aeneasr `gobuffalo/packr@1.22.0` package is reporting a vulnerability and the tests are failing [see](https://app.circleci.com/pipelines/github/ory/fosite/520/workflows/d0318424-309c-403e-b961-319071a2bc76/jobs/1657):
> 
> ```
> pkg:golang/github.com/gobuffalo/packr@1.22.0
> 1 known vulnerabilities affecting installed version
> ```

Looks like this was fixed in v2.3.2 / v1.30.0 / v1.26.0: https://github.com/gobuffalo/packr/commit/f58136c5e12b1db544759732e2a43b4a7c8cebeb

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
🙏

**Comment by mitar** [comment]
Thanks for doing a followup!

**Comment by narg95** [comment]
You are welcome!

**Pull request merged**
