### PR TITLE
Add Argon2 Hasher

### PR DESCRIPTION
**Pull request by MatthewHartstonge**
Implements an Argon2 based Hasher for fosite!

## Development Notes
Issues related to building and developing on Windows:
- **For Argon2 Hasher to work on Windows you will require a compatible CGO environment.**
### For Linux
- Install gcc

### For 32-bit Windows:
- Install [MinGW for x86](https://sourceforge.net/projects/mingw/files/latest/download?source=files)
- Add `C:\MinGW\bin` to path
- Select and install `gcc-core`
- Select and install `gcc-g++`
- Build successfully!

### For 64-bit Windows:
- Install [Cygwin]()
- Add `C:\cygwin64\bin` to path
- Select and Install `x86_64-w64-mingw32-gcc-core`
- Select and Install `x86_64-w64-mingw32-gcc-g++`
- Change all file names in `C:\cygwin64\bin` by removing `x86_64-w64-mingw32-` which is prepended to all files we need to use..
- Build successfully!

### CODE REVIEW

**Comment by MatthewHartstonge** [comment]
Seems the request to coveralls failed under CI on `Go 1.7`, yet worked happily under [my travis build](https://travis-ci.org/MatthewHartstonge/fosite). Everything was clear on 1.8. 
Maybe an intermittent failure with coveralls?

**Comment by arekkas** [comment]
Thank you for your contribution!

My first question is if this implies that, in order to get fosite running on windows, people always need to install cygwin/mingw first? If so, I would like to put this addition into a separate repo and hint to it in the readme, because it will make it much harder to compile fosite-dependent tools such as hydra on windows.

**Comment by MatthewHartstonge** [comment]
Thanks!

As for windows - yes, this is a very real problem. (Currently what I developed this contribution on)
Currently there is no pure-go implementation of the Argon2 1.3 spec (That I know of..) and so have to use a C binding implementation, hence compliation via GCC. 👎

Seperate repo sounds like a good solution though! 😄

**Comment by arekkas** [comment]
Ok cool, feel free to create your own repo, maybe add a little docs on how to integrate it and then we'll add it to the fosite readme :)

**Comment by arekkas** [comment]
As per discussion above, I'll close this PR. If you have everything in place feel free to create a new one! In any case, thank you so much for your contribution to the fosite community :)

**Comment by MatthewHartstonge** [comment]
See: https://github.com/MatthewHartstonge/hasher 👌

**Pull request closed without merging**
